export enum ReportModules {
  frontPage = "FrontPage",
  infoPage = "InfoPage",
  clientModule = "ClientModule",
  controllerModule = "ControllerModule",
  infoModule = "InfoModule",
  statementPage = "StatementPage",
  statementModule = "StatementModule",
  instrumentModule = "InstrumentModule",
  controlModule = "controlModule",
  skjemaPage = "skjemaPage",
  skjemaItemSplit = "skjemaItemSplit",
  measurementPage = "measurementPage",
  inlineMeasurementModule = "inlineMeasurementModule",
  extendedMeasurementModule = "extendedMeasurementModule",
  attachmentModule = "attachmentModule",
  infoAttachmentModule = "infoAttachmentModule",
}
